# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0023_seed_default_user_sectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="chief",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="support",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
