# Generated by Django 5.0.7 on 2026-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0025_seed_online_lookup_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
