# Generated by Django 5.0.7 on 2026-06-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0026_satisfactionsurvey_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shift_schedules', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_schedules', to='schedules.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_shift_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('CHIEF', 'Chefe'), ('AGENT', 'Agente'), ('SUPPORT', 'Apoio')], max_length=16)),
                ('from_member_id', models.PositiveIntegerField()),
                ('from_member_name', models.CharField(max_length=180)),
                ('to_member_id', models.PositiveIntegerField()),
                ('to_member_name', models.CharField(max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_shift_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='schedules.shiftschedule')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_shift_swap_requests', to='schedules.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shiftschedule',
            index=models.Index(fields=['date', 'team'], name='schedules_sh_date_team_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftschedule',
            constraint=models.UniqueConstraint(fields=('date', 'team'), name='unique_shift_schedule_date_team'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['status', 'created_at'], name='shift_sw_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['schedule', 'member_type'], name='shift_sw_sched_type_idx'),
        ),
    ]
