# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0032_service_order_only_realized_agendas"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationreport",
            name="approximate_public",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="educationreport",
            name="materials_removed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="educationreport",
            name="materials_spent",
            field=models.TextField(blank=True),
        ),
    ]
