# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0033_educationreport_materials_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationreport",
            name="distribution_materials_distributed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="educationreport",
            name="distribution_materials_removed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="educationreport",
            name="equipment_materials_distributed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="educationreport",
            name="equipment_materials_removed",
            field=models.TextField(blank=True),
        ),
    ]
