# Generated by Django 5.0.7 on 2026-06-18 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0035_educationaction_grouped_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationreport',
            name='accessibility_conditions_met',
            field=models.CharField(blank=True, choices=[('YES', 'Sim'), ('NO', 'Não')], max_length=3),
        ),
        migrations.CreateModel(
            name='AccessibilityBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_location', models.CharField(blank=True, max_length=220)),
                ('external_responsible', models.CharField(blank=True, max_length=160)),
                ('external_responsible_phone', models.CharField(blank=True, max_length=160)),
                ('external_email', models.EmailField(blank=True, max_length=254)),
                ('requester_cpf', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessibility_blocks', to='schedules.agenda')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessibility_blocks', to='schedules.educationreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'institution_location'], name='schedules_a_is_acti_5c56ed_idx'), models.Index(fields=['is_active', 'external_email'], name='schedules_a_is_acti_06917e_idx'), models.Index(fields=['is_active', 'requester_cpf'], name='schedules_a_is_acti_7700c0_idx')],
            },
        ),
    ]
