# Generated by Django 5.0.7 on 2026-06-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0040_alter_educationreport_breathalyzers'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilityblocklist',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddIndex(
            model_name='accessibilityblocklist',
            index=models.Index(fields=['is_active', 'address'], name='schedules_a_is_acti_068158_idx'),
        ),
    ]
