# Generated by Django 5.1.4 on 2026-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0042_agenda_accessibility_rejection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agenda',
            new_name='schedules_a_accessi_09c3b9_idx',
            old_name='schedules_a_access_9d6988_idx',
        ),
        migrations.AddField(
            model_name='educationreport',
            name='general_observations',
            field=models.TextField(blank=True),
        ),
    ]
