# Generated by Django 5.1.4 on 2026-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0043_rename_schedules_a_access_9d6988_idx_schedules_a_accessi_09c3b9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dinâmica',
                'verbose_name_plural': 'Dinâmicas',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['name'], 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
    ]
