# Generated by Django 5.1.4 on 2026-06-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0047_satisfaction_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='origin',
            field=models.CharField(choices=[('INTERNAL', 'Interna'), ('PUBLIC_FORM', 'Formulario publico'), ('WHATSAPP', 'WhatsApp'), ('PHONE', 'Telefone'), ('EMAIL', 'E-mail'), ('DOCUMENT', 'Oficio'), ('OTHER', 'Outra')], db_index=True, default='INTERNAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='start_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='answered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
