# Generated by Django 5.0.7 on 2026-07-01 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0049_region_municipality_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='satisfactionsurvey',
            index=models.Index(fields=['moderation_status', 'answered_at'], name='survey_status_answered_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionsurvey',
            index=models.Index(fields=['team', 'answered_at'], name='survey_team_answered_idx'),
        ),
    ]
