# Generated by Django 5.0.7 on 2026-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0055_educationreport_no_photo_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationreport',
            name='street_action_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
