# Generated by Django 5.0.7 on 2026-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0056_educationreport_street_action_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='street_action_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
