# Generated by Django 5.1.4 on 2026-07-14 19:20

from django.db import migrations

def migrate_submitted_to_approved(apps, schema_editor):
    EducationReport = apps.get_model('schedules', 'EducationReport')
    EducationReport.objects.filter(status='SUBMITTED').update(status='APPROVED')

def reverse_migrate(apps, schema_editor):
    EducationReport = apps.get_model('schedules', 'EducationReport')
    EducationReport.objects.filter(status='APPROVED').update(status='SUBMITTED')


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0058_educationreport_review_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_submitted_to_approved, reverse_migrate),
    ]
