# Generated by Django 5.1.4 on 2026-07-14 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0059_migrate_submitted_to_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationreport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviado')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='schedules.educationreport')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
