# Generated by Django 5.1.4 on 2026-07-14 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0060_alter_educationreport_status_reportstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftManualInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('CHIEF', 'Chefe'), ('AGENT', 'Agente'), ('SUPPORT', 'Apoio')], max_length=16)),
                ('member_id', models.PositiveIntegerField()),
                ('member_name', models.CharField(max_length=180)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_manual_inclusions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_inclusions', to='schedules.shiftschedule')),
            ],
            options={
                'ordering': ['member_name'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'member_type', 'member_id'), name='unique_shift_inclusion_member')],
            },
        ),
    ]
