# Generated by Django 5.1.4 on 2026-07-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0061_shiftmanualinclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='checked_members',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
