# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("CREATE", "Criacao"),
                            ("UPDATE", "Alteracao"),
                            ("DELETE", "Exclusao"),
                            ("STATUS_CHANGE", "Mudanca de status"),
                            ("PASSWORD_LINK", "Link de senha"),
                            ("PASSWORD_RESET", "Recuperacao de senha"),
                            ("SET_PASSWORD", "Definicao de senha"),
                            ("EMAIL", "Envio de e-mail"),
                            ("REPORT_EXPORT", "Exportacao de relatorio"),
                        ],
                        max_length=32,
                    ),
                ),
                ("module", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["-created_at"], name="accounts_au_created_25d7e5_idx"),
                    models.Index(fields=["action", "module"], name="accounts_au_action_d9594d_idx"),
                    models.Index(fields=["user", "-created_at"], name="accounts_au_user_id_728d71_idx"),
                ],
            },
        ),
    ]
