# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("MANAGER", "Gestor"),
                    ("SUPERVISOR", "Supervisor"),
                    ("USER", "Usuário comum"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
