# Generated by Codex on 2026-06-02

from django.db import migrations


def normalize_public_request_user(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email="solicitacao.publica@agenda.local").update(
        role="USER",
        is_active=False,
        is_staff=False,
        is_superuser=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_role_manager"),
    ]

    operations = [
        migrations.RunPython(normalize_public_request_user, migrations.RunPython.noop),
    ]
