# Generated by Django 5.0.7 on 2026-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_normalize_public_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Gestor'), ('SUPERVISOR', 'Supervisor'), ('VISITOR', 'Visitante'), ('USER', 'Usuário comum')], default='USER', max_length=20),
        ),
    ]
